### ISSUE TITLE
The version is 2.0.1

### ISSUE THREAD

**Issue by yanjin1234** [niedev/RTranslator#18]
There was an error loading the files of the models for translation and speech recognition,try restarting the app,if the problem persists then reset it.

**Comment by niedev** [comment]
Sometimes there can be errors with the download of files (in the future I will improve the detection and management of these errors), for now the only way to resolve is to uninstall and reinstall the application, and make sure to keep the phone with the screen turned on and with RTranslator open during the download (the download also works in the background, but doing so minimizes the possibility of errors).

**Comment by MaximMonin** [comment]
Actually it is real problem. Already reinstalled 3 times, and download process always stopping in the middle when trying to switch to new file. "Check files and repeat" button in download dialog will be usefull.

**Comment by niedev** [comment]
Thanks for the feedback, I will definitely do this in the future (probably with RTranslator 2.1).  

However it is not normal that it fails so often, have you checked if you have enough free GB on your phone? (at least 2-3GB are required, because files are duplicated and then deleted during transfer from external to internal memory of the app) If this is not the case, do you have an SD card on your phone and have you set it to automatically save applications data to that SD card?

**Comment by MaximMonin** [comment]
I have Xiaomi Redme Note 11 with 4gb+2gb/128gb. With 70Gb available on sd card. Yes i got message, that application can be crashed.

**Comment by niedev** [comment]
How many free GB do you have in your phone's internal memory?

**Comment by MaximMonin** [comment]
> How many free GB do you have in your phone's internal memory?

Actually cannot find a way to identify it on hyper os. I restarted phone it downloaded everything. But at the end I got error. Application shows that 1.20 gb used by application. Maybe something wrong with my phone. Issue closed for me.
