### ISSUE TITLE
Where are the Whisper models defined?

### ISSUE THREAD

**Issue by soupslurpr** [niedev/RTranslator#25]
Hi, this app is pretty cool nice job, I was amazed by it's speed even though I read it's using the small Whisper model. For this reason I wanted to explore switching to using onnxruntime for running Whisper in my app [Transcribro](https://github.com/soupslurpr/Transcribro) to see if I can switch to a bigger model while keeping the same speed (currently using tiny q8_0 with whisper.cpp). However, I couldn't find where the code that uses the Whisper model or how to use the Whisper model in onnxruntime. Could you direct me to an example or where this app uses the Whisper model? Thanks!

**Comment by JingziC** [comment]
I suppose that this app uses onnx runtime by importing [ai.onnxruntime in Java](https://onnxruntime.ai/docs/get-started/with-java.html). The code using whisper in onnxruntime might be [Recognizer.java](https://github.com/niedev/RTranslator/blob/v2.00/app/src/main/java/nie/translator/rtranslator/voice_translation/neural_networks/voice/Recognizer.java).

**Comment by niedev** [comment]
@soupslurpr Thank you for the appreciation, I like your project too. As @JingziC said, Whisper's inference logic is all inside the Recognizer class.

**Comment by soupslurpr** [comment]
@niedev Okay I see, but where do you get the Whisper models in onnx format or how do you convert it?

**Comment by niedev** [comment]
To get the whisper models you can just download them in the [release of RTranslator 2.0](https://github.com/niedev/RTranslator/releases/tag/2.0.0) (all the models that start with "Whisper_".

If you want to convert them by yourself it is complicated, because I used [Intel's quantized encoder and decoder](https://huggingface.co/Intel/whisper-small-int8-dynamic-inc) (Whisper_encoder.onnx and Whisper_decoder.onnx). Then, from Whisper converted from pytorch to onnx, I extracted the components that generate the kV cache of the encoder (Whisper_cache_initializer.onnx). Then I converted Whisper to onnx with Microsoft Olive, and from there I extracted the components for generating the log-mel (Whisper_initializer.onnx) and the detokenizer (Whisper_detokenizer.onnx). 

I could have directly used just the single .onnx model generated by Olive, but that model consumes 1.3GB of RAM, while using all these components separately it consumes: 
- 0.5GB of RAM with arena deactivated (slower inference)
- 0.9GB of RAM with arena activated (faster inference)

But if you need just Whisper small you can simply use the models in the release of RTranslator that I linked above.

**Comment by soupslurpr** [comment]
For now I'll wait for Whisper to get an official example in onnxruntime as I want to easily use other sizes or finetunes if needed. Thanks for the help though!
