### ISSUE TITLE
Is it possible to add languages?

### ISSUE THREAD

**Issue by leandro-cyberproject** [niedev/RTranslator#34]
As stated in the title, is it possible to add languages? For example hungarian (magyar)?

If it is at all possible, how time consuming is it?

**Comment by niedev** [comment]
Using fine tuning yes, [here ](https://cointegrated.medium.com/how-to-fine-tune-a-nllb-200-model-for-translating-a-new-language-a37fc706b865) is a tutorial.

I don't know how long it would take since I've never done fine tuning (in the article it says that it takes about 24 hours of computing time, but it definitely takes more time to find the right data, set everything up and more).

For now though I'm avoiding fine tuning because I don't think I'll keep the NLLB models for too long, but as new translation models come out I'll replace them.

However I'm thinking of adding more languages in the future ​​simply by separating the list of WalkieTalkie and Conversation languages ​​from the text translation ones (since for now the list of languages ​​is unique, so it only contains those compatible with both NLLB and Whisper).
