### ISSUE TITLE
[Feature Request] Support screen-based translation and Voice transcribing

### ISSUE THREAD

**Issue by ThaDaVos** [niedev/RTranslator#35]
Would be cool if the app could translate text directly on screen without the need to copy-paste it - or even voice transcribing and translating for voice messages.

**Comment by niedev** [comment]
I don't know how feasible these things would be for a non-system app (since it should always be open and on top of any app, and the voice message thing would only be possible through direct collaboration with the developers of the messaging apps).

Plus for now, I prefer to focus on improving the features that the app already has rather than inserting new ones.
