### ISSUE TITLE
HarmonyOS 4  open error

### ISSUE THREAD

**Issue by alanOO7** [niedev/RTranslator#42]
![Screenshot_20240629_083842_nie translator rtranslator](https://github.com/niedev/RTranslator/assets/10321054/bb4d0489-bbc6-4e09-bfac-945281d4e265)
😅HarmonyOS 4

**Comment by joyk21** [comment]
目前只支持Google TTS，没有内置Google TTS的用不了

**Comment by niedev** [comment]
My models are downloaded from GitHub, and [from what I have seen](https://www.reddit.com/r/China/comments/v8fv0p/why_is_github_so_slow_in_china_recently/), accessing GitHub from China has some problems, in the future I will try to improve the download by giving the possibility to re-download only the individual damaged models and to manually insert the models, but for now the only solution to solve the problem is to reset the app and redownload everything 🥲.

**Comment by niedev** [comment]
@alanOO7 The [new release](https://github.com/niedev/RTranslator/releases/tag/2.0.3) that improves the download is out! Let me know if this solves your problem.
