### ISSUE TITLE
Connect devices by internet

### ISSUE THREAD

**Issue by ILG2021** [niedev/RTranslator#5]
Nice job, niedev. But I find that devices are connect by bluetooth. It is very constricted, can you add the feature that users can have conversations on internet? Just like microsoft translate.

https://play.google.com/store/apps/details?id=com.microsoft.translator&hl=zh_CN&gl=CA

**Comment by niedev** [comment]
Thank you 😁!
For the internet you are right, in fact in the past I tried to implement a P2P connection through the internet but the problem is that to use it every user would have to change the Nat and the firewall of his router, moreover in the case of a 4g connection it would not even be possible to change these settings (since in that case the Nat and the firewall are managed by the network provider).  

The alternative would be to use a server (that is what Microsoft translate does), but since I don't make any money from the app (all the money goes directly to Google for translation and speech recognition) I couldn't afford it.
