### ISSUE TITLE
[Feature request]translate for the GalleryImageSelector

### ISSUE THREAD

**Issue by Replica0110** [niedev/RTranslator#56]
hello!niedev.
I found that the GalleryImageSelector seems to only support English. I have tried to add multilingual support to it (currently supporting both English and Simplified Chinese). You can find my fork [here](https://github.com/Agiens02/GalleryImageSelector). I'm not sure if this will cause any other issues, but I have no problem running it on my own phone. Would you consider adding multilingual support to the selector as well?
In addition, the [RTranslator notification](https://github.com/niedev/RTranslator/blob/v2.00/app/src/main/java/nie/translator/rtranslator/voice_translation/VoiceTranslationActivity.java#L609) still uses hardcode, and I have attempted to translate it [here](https://github.com/Agiens02/RTranslator/blob/v2.00/app/src/main/java/nie/translator/rtranslator/voice_translation/VoiceTranslationActivity.java#L609).
I am still learning Java. If the above suggestions will cause any problems, please let me know.

**Comment by niedev** [comment]
Hi @Agiens02!

For now, adding languages ​​to the image selection in this way is a bit cumbersome (since for each change to the languages ​​I would have to release a new version of the GalleryImageSelector), so in the future to do this I will integrate the GalleryImageSelector code into RTranslator, or I will add the ability to specify the selection strings externally to GalleryImageSelector.

For the notification instead, there is no problem, if you want to make a pull request however you should make another fork and change only that (since I noticed that in your fork there are other changes that would not be accepted), otherwise I can make this change myself, there is no problem, let me know.

**Comment by Replica0110** [comment]
@niedev 
Thank you for your suggestion. I have pulled a new branch and only modified the notification section.and I have opened a pull request.
I have not studied Italian, so the translation of Italian relies on machine translation. If there are any problems, please let me know.
