### ISSUE TITLE
[Question]Why does the software stop when it downloads NLLB encoder up to 0.69G and suggests that there is no internet?

### ISSUE THREAD

**Issue by bugxzhu** [niedev/RTranslator#71]
Why does the software stop when it downloads NLLB encoder up to 0.69G and suggests that there is no internet?
Is there a way to just download the model and put it in a directory?This would avoid problems with downloading.

**Comment by bugxzhu** [comment]
![Uploading WechatIMG355.jpg…]()

**Comment by bugxzhu** [comment]
![WechatIMG355](https://github.com/user-attachments/assets/ba96cc4a-052d-4722-b98f-6b16bfba7aec)

**Comment by niedev** [comment]
> Why does the software stop when it downloads NLLB encoder up to 0.69G and suggests that there is no internet?

Some regions, like China, [have problems with the download](https://www.reddit.com/r/China/comments/v8fv0p/why_is_github_so_slow_in_china_recently/).

> Is there a way to just download the model and put it in a directory?This would avoid problems with downloading.

Yes! See [here](https://github.com/niedev/RTranslator/blob/v2.00/Sideloading.md) for the instructions.

**Comment by bugxzhu** [comment]
> > Why does the software stop when it downloads NLLB encoder up to 0.69G and suggests that there is no internet?
> 
> Some regions, like China, [have problems with the download](https://www.reddit.com/r/China/comments/v8fv0p/why_is_github_so_slow_in_china_recently/).
> 
> > Is there a way to just download the model and put it in a directory?This would avoid problems with downloading.
> 
> Yes! See [here](https://github.com/niedev/RTranslator/blob/v2.00/Sideloading.md) for the instructions.

@niedev I don't think so。Because I already use vpn.
`NLLB_encoder.onnx失败 - 需要获得授权`

Is this error an authorization issue?
others can be downloaded。

**Comment by bugxzhu** [comment]
![1725861008425](https://github.com/user-attachments/assets/3bb706d7-7402-4d3b-9bd1-d1e7f1a4946b)
@niedev

**Comment by niedev** [comment]
> @niedev I don't think so。Because I already use vpn. `NLLB_encoder.onnx失败 - 需要获得授权`

I tested the download on my phone and it works fine, after the error message did you try the download again and it always gets stuck on the same file? (sometimes the download can have random errors and retrying it works), also did you try to download it from PC and do sideloading?

**Comment by bugxzhu** [comment]
@niedev thanks。I success to download it on PC。
but  the “Android/data/nie.translator.rtranslator/files”  folder cannot be accessed. Can you provide an additional path for uploading models in the app?

**Comment by niedev** [comment]
@bugxzhu For now that's the only path, in the future I will probably add another, anyway it is strange that it isn't accessible, what OS do you have on PC?

**Comment by bugxzhu** [comment]
@niedev It has little to do with the OS.It's because of a limitation of the phone's system that prevents access to the data directory in the Android directory, which is locked for security reasons.

**Comment by niedev** [comment]
@bugxzhu it may have to do with the OS of your PC, because normally that folder is hidden in the phone itself (not for security reason but to preventing people from breaking an app accidentally), but [it is accessible with a PC](https://support.google.com/files/thread/242391122/i-want-to-open-my-android-data-folder-but-i-can-t-how-can-i-access-it?hl=en) (I don't make a tutorial without testing it and doing some research)

**Comment by lrq3000** [comment]
I had the same issue today. And I could debug and fix it.

It happened after I paused the download for one day, because I didn't have time nor the storage space to complete the download and I didn't know before launching how much space was needed.

Then when i relaunched the app one day later and restarted the download, it progressed a bit, then failed similarly, telling me that my internet connection had issues.

I retried several times to no avail. It alwayt failed at the exact same percentage, hence why I suspected there was a bug, not a network error. 

Finally I suspected that maybe the app started downloading a part of the data and is somehow tripping up when trying to resume downloading the rest, maybe a checksum verification failure because of improper download resuming, so I went to Android's applications listing in Settings and cleared all data (not just the cache) for RTranslator (after force killing it). Then I restarted the app and everything was working fine.

So i would suggest to maybe offer a way in the app to clear all data at this stage if the download fails several times in a row.

**Comment by niedev** [comment]
@lrq3000 Thank you for reporting your solution, but this is strange, since the app downloads one model at a time and then, as you also said, verifies the integrity of that model. However the application does not have a real mechanism to resume downloads, when the download is paused, it simply cancels the download of the current model and when the resume button is pressed it re-runs it from scratch (starting from that model, the previously downloaded ones have already been verified and will remain), so the source of the bug could be more complicated than that, if more reports come in I will investigate on this.

**Comment by lrq3000** [comment]
I suspected that the software was intending to restart the whole downloading process, my guess is that a file is left behind that is not accounted for in case of a restart and if this file is corruptet, it never gets properly redownloaded, and so it trips up one of the integrity checks.

If that's the case, it will be hard to debug. Maybe AI can help with finding this by simulation of a unit test.

**Comment by niedev** [comment]
If you mean that when the download is interrupted the old file is verified instead of the new one fully downloaded, I think this is not the case, because I did a quick test by canceling the download of a file before it was completed and the download was successful. To verify the integrity of a model file I load it directly into OnnxRuntime, and if it does not give errors then the verification continues, so if the old file was verified, since it had been partially downloaded the verification would have failed.
Plus, it would be very difficult to debug (with or without AI I suppose) since the problem is not replicable (and not being replicable we do not even know how frequent it is), therefore I will investigate only when other reports arrive, hopefully with a way to replicate the bug, anyway thank you for the help.
