### ISSUE TITLE
[BUG]basic english translate seems not working

### ISSUE THREAD

**Issue by jas0nw5ng** [niedev/RTranslator#77]
**Describe the bug**
As title, please refer snapshot for evidence

**Smartphone**
 - Device: [Xiaomi K60 Pro]
 - Android OS version: [Android 14]
 - TTS used: [nothing]
 - Version of the app: [2.1.0]

**Additional context**
Hope this app become production ready soon.

![rtranslator_basic_english.png](https://github.com/user-attachments/assets/48a3c82e-797f-4386-9dd2-0fcc72e19880)

**Comment by niedev** [comment]
Hi, thanks for reporting a bug, could you give me more details? I don't know Chinese so I don't understand much from the screens, I need the following informations:
- Which languages ​​did you select
- What do the screenshots translation results correspond to (in English)?

**Comment by jas0nw5ng** [comment]
It is translation from English to Chinese is totally incorrect,  you can try comparing with bing translate or Google translate for difference.

**Comment by niedev** [comment]
@ajasonwang Ok, but using other translators is not the best way to understand this kind of errors (because they can also make mistakes or give meaning to translations that don't have any), can you tell me what words in English the wrong translations correspond to? Or do they just make no sense and there is no translation? Also with longer sentences do you have the same problem? Because I need to understand if the translation errors depend on the NLLB model or the tokenizer.

**Comment by jas0nw5ng** [comment]
What I am talking about is those commonly used and basic words translation, RTranslator give totally nonsense result, for example you can simply trying translate words like china and American.

**Comment by niedev** [comment]
@ajasonwang So with longer sentences you don't have problems right? Because in this case it's nllb's fault and I can't do much about that, in general nllb works much better for longer sentences and has problems with single words.

**Comment by jas0nw5ng** [comment]
> @ajasonwang So with longer sentences you don't have problems right? Because in this case it's nllb's fault and I can't do much about that, in general nllb works much better for longer sentences and has problems with single words.

longer sentences translation is way better but still not accurate enough, but it's usable.

**Comment by Eyion** [comment]
In intercom mode, I choose to translate from Chinese to English, but the translation result is very bad. What is the reason for this problem? How can I improve it?

**Comment by niedev** [comment]
> In intercom mode, I choose to translate from Chinese to English, but the translation result is very bad. What is the reason for this problem? How can I improve it?

If you try to translate the same sentence written in the text translation mode the result is good?

**Comment by Eyion** [comment]
Yes, the result is better. Another problem is that when in intercom mode, it seems that the Bluetooth headset can not receive the voice, only close to the mobile phone to be recognized, is this correct?

**Comment by niedev** [comment]
Ok, so probably you can improve the speech recognition quality by increasing, in the app settings, the sensitivity, the end of voice timeout and the voice anticipation duration, if this not works it means that Whisper's quality with Chinese is not so good, and for now I can't do nothing about it. 
For walkie talkie mode, in that case the mic used is always the phone's microphone, because that mode is designed for two people talking, and the mic of an headphone wouldn't capture the other person voice well, the headphone mic is only used in the conversation mode.

**Comment by Eyion** [comment]
> Ok, so probably you can improve the speech recognition quality by increasing, in the app settings, the sensitivity, the end of voice timeout and the voice anticipation duration, if this not works it means that Whisper's quality with Chinese is not so good, and for now I can't do nothing about it. For walkie talkie mode, in that case the mic used is always the phone's microphone, because that mode is designed for two people talking, and the mic of an headphone wouldn't capture the other person voice well, the headphone mic is only used in the conversation mode.

I increased the duration of the corresponding settings as you said, and the situation has improved. Thank you.
