### ISSUE TITLE
[Question]是完全免费的吗 可以实现完全离线的功能吗 能不能发布一个包含下载模型的代码

### ISSUE THREAD

**Issue by Cui0526** [niedev/RTranslator#88]
- [ ] The question is written in English (I can translate what you say, but questions written in English are easier to read for the other users).

Write here the question.

**Comment by niedev** [comment]
Hi, yes, it is totally free and totally offline after you initially download the models (I can't integrate them into the app because an apk can weigh a maximum of 200mb, and the models weigh 2gb). [Here](https://github.com/niedev/RTranslator/releases/tag/2.0.0), in assets, are all the models used by the app.
